# Generated by Django 2.1.15 on 2020-04-05 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200405_0709'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='image',
            new_name='images',
        ),
    ]
